''' Utility module '''
import collections

Recipe = collections.namedtuple('Recipe', 'material recipe cost')

WORLDS_TOKEN = 'MATERIAL_337'
NIGHT_AND_DAWN_TOKEN = 'MATERIAL_347'
MECHA_KINGDOMS_TOKEN = 'MATERIAL_358'

WOLRDS_CHAMP_SHARD_RECIPE = Recipe('MATERIAL_337', 'MATERIAL_337_FORGE_33', 50)
NIGHT_AND_DAWN_CHAMP_SHARD_RECIPE = Recipe('MATERIAL_347', 'MATERIAL_347_FORGE_19', 50)
MECHA_KINGDOMS_CHAMP_SHARD_RECIPE = Recipe('MATERIAL_358', 'MATERIAL_358_FORGE_29', 50)

RECIPIES = [
    WOLRDS_CHAMP_SHARD_RECIPE,
    NIGHT_AND_DAWN_CHAMP_SHARD_RECIPE,
    MECHA_KINGDOMS_CHAMP_SHARD_RECIPE,
]
